tclean:
 vis: "sim_data_VLA.ms"
 imagename: "test" 
 imsize: 512 
 cell: "12.0arcsec"
 specmode: "cube" 
 interpolation: "nearest"
 nchan: 5 
 start: "1.0GHz" 
 width: "0.2GHz" 
 pblimit: -0.00001
 deconvolver: "hogbom"
 niter: 5000
 cyclefactor: 2 
 scales:
  - 0
  - 3
  - 10
 interactive: 0